In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from matplotlib import dates

import seaborn as sns 
import matplotlib.style as style

from fbprophet import Prophet
pd.plotting.register_matplotlib_converters() # required to fix plotting bug introduced by prophet

from fbprophet.diagnostics import cross_validation
from fbprophet.diagnostics import performance_metrics
from fbprophet.plot import plot_cross_validation_metric

Importing plotly failed. Interactive plots will not work.

In [3]:
df_nat=pd.read_csv('../data/nat.csv')

In [4]:
df_nat

,DateTime,Périmètre,Consommation,Fioul,Charbon,Gaz,Nucléaire,Eolien,Solaire,Hydraulique,...,Gaz - TAC,Gaz - Cogén.,Gaz - CCG,Gaz - Autres,Hydraulique - Fil de l?eau + éclusée,Hydraulique - Lacs,Hydraulique - STEP turbinage,Bioénergies - Déchets,Bioénergies - Biomasse,Bioénergies - Biogaz
0,2013-01-01 00:30:00,France,59674.0,473.0,-31.0,3448.0,50485.0,4178.0,0.0,7528.0,...,-3.0,2858.0,499.0,94.0,5555.0,1214.0,758.0,478.0,130.0,161.0
1,2013-01-01 01:00:00,France,57877.0,472.0,-32.0,3231.0,50070.0,4045.0,0.0,7136.0,...,-3.0,2861.0,279.0,94.0,5582.0,963.0,591.0,475.0,126.0,159.0
2,2013-01-01 01:30:00,France,57755.0,473.0,-31.0,3240.0,50425.0,3967.0,0.0,6704.0,...,-4.0,2866.0,284.0,94.0,5453.0,735.0,515.0,477.0,125.0,160.0
3,2013-01-01 02:00:00,France,57243.0,472.0,-31.0,3230.0,50247.0,3906.0,0.0,6385.0,...,-3.0,2860.0,279.0,94.0,5420.0,752.0,212.0,486.0,123.0,159.0
4,2013-01-01 02:30:00,France,56660.0,472.0,-31.0,3224.0,49890.0,3822.0,0.0,6150.0,...,-4.0,2853.0,281.0,94.0,5261.0,688.0,199.0,479.0,124.0,160.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
105108,2018-12-31 21:30:00,France,60580.0,170.0,12.0,3825.0,55679.0,1406.0,-2.0,4648.0,...,4.0,2497.0,1210.0,114.0,3860.0,789.0,0.0,556.0,314.0,295.0
105109,2018-12-31 22:00:00,France,59901.0,146.0,11.0,3568.0,55404.0,1452.0,-2.0,4632.0,...,4.0,2496.0,950.0,117.0,3818.0,815.0,0.0,556.0,314.0,296.0
105110,2018-12-31 22:30:00,France,60939.0,146.0,11.0,3886.0,55186.0,1569.0,-2.0,4451.0,...,4.0,2495.0,1269.0,118.0,3759.0,692.0,0.0,557.0,312.0,296.0
105111,2018-12-31 23:00:00,France,63977.0,146.0,11.0,3910.0,55589.0,1537.0,-2.0,5148.0,...,4.0,2494.0,1296.0,116.0,3716.0,1432.0,0.0,557.0,318.0,296.0
105112,2018-12-31 23:30:00,France,63803.0,146.0,12.0,3452.0,55404.0,1543.0,-2.0,4688.0,...,4.0,2470.0,863.0,115.0,3531.0,1157.0,0.0,557.0,316.0,293.0

In [5]:
conso=df_nat[['DateTime','Consommation']]

In [6]:
conso

                   DateTime  Consommation
0       2013-01-01 00:30:00       59674.0
1       2013-01-01 01:00:00       57877.0
2       2013-01-01 01:30:00       57755.0
3       2013-01-01 02:00:00       57243.0
4       2013-01-01 02:30:00       56660.0
...                     ...           ...
105108  2018-12-31 21:30:00       60580.0
105109  2018-12-31 22:00:00       59901.0
105110  2018-12-31 22:30:00       60939.0
105111  2018-12-31 23:00:00       63977.0
105112  2018-12-31 23:30:00       63803.0

[105113 rows x 2 columns]